on:
  push:
    branches: [main, github-ci]
  pull_request:
    branches: [main, github-ci]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v7
        with:
          node-version: "16"

      - name: Build the project
        run: |
          npm ci
          npm run build
          npx esbuild $GITHUB_WORKSPACE/packages/cli/lib/index.js --bundle --platform=node --target=node16 --external:emitter --outfile=$RUNNER_TEMP/dist/app/gjallarhorn.js

      - name: Construct dist
        # TODO: add gjallarhorn.cmd
        run: |
          cp -r $GITHUB_WORKSPACE/node_modules/serve-index/public $RUNNER_TEMP/dist/app
          cp -r $GITHUB_WORKSPACE/packages/core/lib/client $RUNNER_TEMP/dist
          cp $GITHUB_WORKSPACE/static/launcher.js $RUNNER_TEMP/dist

      - name: Download and unzip node to dist
        run: |
          curl -o $RUNNER_TEMP/node.zip https://nodejs.org/dist/v16.20.2/node-v16.20.2-win-x64.zip
          unzip $RUNNER_TEMP/node.zip -d $RUNNER_TEMP/dist

      - name: Create zip
        run: |
          cd $RUNNER_TEMP/dist
          zip -r gjallarhorn.zip .

      - name: Upload zip
        uses: actions/upload-artifact@v4
        with:
          name: gjallarhorn
          path: $RUNNER_TEMP/dist/gjallarhorn.zip
